spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/McqTestSystem
spring.datasource.username=root
spring.datasource.password=Sanshu3007$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.root=INFO


# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anshu.sachdev.st@gmail.com
spring.mail.password=tqtq etrm bgnt ttjq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true